### ISSUE TITLE
Wrong API call in use for Android 

### ISSUE THREAD

**Issue by leroydev** [shangyilim/cordova-plugin-pincheck#2]
For Android, the following call is done for checking if the device is secured with a code:
> keyguardManager.isKeyguardSecure();

This call however also returns `true` if the SIM card is locked. (source: https://developer.android.com/reference/android/app/KeyguardManager.html#isKeyguardSecure())

This can be fixed by changing the call to:
> keyguardManager.isDeviceSecure();

**Comment by shangyilim** [comment]
Hello! Thanks for that. I'll take a look and see and will update it ;)

**Comment by leroydev** [comment]
@shangyilim I just noticed that `isKeyguardLocked` was added in API level 16, whereas `isDeviceLocked` was added in API level 23. Since API level 23 means Android 6.0 and up, you can't just replace the call and keep backwards compatibility. Maybe use `isDeviceLocked` when the API level is 23 or higer and fallback to `isKeyguardLocked` otherwise?

**Comment by timbru31** [comment]
@leroydev can you make a PR - stumbled across the same issue ;)

**Comment by shangyilim** [comment]
that would be helpful if you could issue a PR. Thanks!

**Comment by leroydev** [comment]
@timbru31 @shangyilim I'll try to make a PR this weekend. 👍
